# -*- coding: utf-8 -*-
import glob
import os

html_files = glob.glob('c:/Users/HP/web_nghe_nhac/src/templates/*.html')

# Danh sách replacement siêu chi tiết
replacements = [
    # Titles
    ('Quản lý Dữ liệu Ã\x82m nhạc', 'Quản lý Dữ liệu Âm nhạc'),
    ('Quản lý Dá»¯ liá»‡u Ã\x82m nhạc', 'Quản lý Dữ liệu Âm nhạc'),
    ('Quản LÃ½ Ngá»±i DÃ¹ng', 'Quản Lý Người Dùng'),
    ('Quản LÃ½ Nhạc', 'Quản Lý Nhạc'),
    
    # Common words
    ('vÃ ', 'và'),
    ('VÃ ', 'Và'),
    ('Ã ', 'à'),
    ('Ã¡', 'á'),
    ('áº£', 'ả'),
    ('áº¡', 'ạ'),
    ('Ã¢', 'â'),
    ('Ã©', 'é'),
    ('Ã¨', 'è'),
    ('áº½', 'ẽ'),
    ('áº¹', 'ẹ'),
    ('Ã­', 'í'),
    ('Ã¬', 'ì'),
    ('Ã³', 'ó'),
    ('Ã²', 'ò'),
    ('á»', 'ỏ'),
    ('Ãµ', 'õ'),
    ('á»', 'ọ'),
    ('Ã´', 'ô'),
    ('Ãº', 'ú'),
    ('Ã¹', 'ù'),
    ('á»§', 'ủ'),
    ('Å©', 'ũ'),
    ('á»¥', 'ụ'),
    ('Æ°', 'ư'),
    ('á»±', 'ự'),
    ('á»­', 'ử'),
    ('á»«', 'ừ'),
    ('á»©', 'ứ'),
    ('á»¯', 'ữ'),
    ('Ä', 'Đ'),
    ('BÃ i hát', 'Bài hát'),
    ('bÃ i hát', 'bài hát'),
    ('BÃ i Hát', 'Bài Hát'),
    ('BÃ€I HÃT', 'BÀI HÁT'),
    ('thÃªm', 'thêm'),
    ('Thêm', 'Thêm'),
    ('nÃ o', 'nào'),
    ('nÃ y', 'này'),
    ('Đ'áº§u tiên', 'đầu tiên'),
    ('Đ'ỏƒ', 'để'),
    ('báº¯t', 'bắt'),
    ('Đ'áº§u', 'đầu'),
    ('Đ'Ã£', 'đã'),
    ('Đ'ưỏ£c', 'được'),
    ('thÃ nh công', 'thành công'),
    ('káº¿t nỏ'i', 'kết nối'),
    ('Đ'áº¿n', 'đến'),
    ('chỏ§', 'chủ'),
    ('Không thể', 'Không thể'),
    ('Đáº·t', 'Đặt'),
    ('riÃªng tư', 'riêng tư'),
    ('công khai', 'công khai'),
    ('Đang', 'Đang'),
    ('ĐÃ£', 'Đã'),
    ('Quản lý', 'Quản lý'),
    ('ngÆ°á»i dÃ¹ng', 'người dùng'),
    ('Ngá»±i dÃ¹ng', 'Người dùng'),
    ('Ngưỏi dùng', 'Người dùng'),
    ('nghệ sĩ', 'nghệ sĩ'),
    ('Nghệ Sĩ', 'Nghệ Sĩ'),
    ('Nghệ sĩ', 'Nghệ sĩ'),
    ('hoáº±c', 'hoặc'),
    ('yêu thích', 'yêu thích'),
    ('Hỏ" sÆ¡', 'Hồ sơ'),
    ('hỏ" sÆ¡', 'hồ sơ'),
    ('HÃ£y', 'Hãy'),
    ('nhỏ¯ng', 'những'),
    ('Đ'ây', 'đây'),
    ('Tiêu Đ'ỏ', 'Tiêu đề'),
    ('Chưa', 'Chưa'),
    ('thuỏ™c', 'thuộc'),
    ('Ảnh', 'Ảnh'),
    ('Chỏ‰nh sỏ­a', 'Chỉnh sửa'),
    ('chi tiáº¿t', 'chi tiết'),
    ('âœ"', '✓'),
    ('chuyỏƒn', 'chuyển'),
    ('Xóa', 'Xóa'),
    ('khỏi', 'khỏi'),
    ('xóa', 'xóa'),
    ('Tìm', 'Tìm'),
    ('tìm', 'tìm'),
    ('kiáº¿m', 'kiếm'),
    ('tên', 'tên'),
    ('Tên', 'Tên'),
    ('Nháº­p', 'Nhập'),
    ('chỏn', 'chọn'),
    ('Chỏn', 'Chọn'),
    ('tick', 'tick'),
    ('thấy', 'thấy'),
    ('Lỗi', 'Lỗi'),
    ('thông tin', 'thông tin'),
    ('Sửa', 'Sửa'),
    ('Thông Tin', 'Thông Tin'),
    ('Đang tải', 'Đang tải'),
    ('file', 'file'),
    ('mới', 'mới'),
    ('náº¿u', 'nếu'),
    ('muỏ'n', 'muốn'),
    ('thay', 'thay'),
    ('Đ'ỏ•i', 'đổi'),
    ('Giỏ¯', 'Giữ'),
    ('click', 'click'),
    ('nhiỏu', 'nhiều'),
    ('tải', 'tải'),
    ('Không', 'Không'),
    ('thể', 'thể'),
    ('Điỏn', 'Điền'),
    ('vÃ o', 'vào'),
    ('form', 'form'),
    ('Set', 'Set'),
    ('album', 'album'),
    ('genre', 'genre'),
    ('ảnh', 'ảnh'),
    ('có', 'có'),
    ('Láº¥y', 'Lấy'),
    ('hiện tại', 'hiện tại'),
    ('hiỏƒn thị', 'hiển thị'),
    ('Đ'úng', 'đúng'),
    ('cỏ™t', 'cột'),
    ('lưỏ£t nghe', 'lượt nghe'),
    ('ĐÃ£ xóa', 'Đã xóa'),
    ('UI', 'UI'),
    ('dữ liệu', 'dữ liệu'),
    ('cập nhật', 'cập nhật'),
    ('listen count', 'listen count'),
    ('Lịch sử', 'Lịch sử'),
    ('nghe', 'nghe'),
    ('gáº§n', 'gần'),
    ('Đ'ây', 'đây'),
    ('của', 'của'),
    ('bạn', 'bạn'),
    ('Tỏ'i', 'Tối'),
    ('Đ'a', 'đa'),
    ('mới', 'mới'),
    ('nháº¥t', 'nhất'),
    ('Thỏi gian', 'Thời gian'),
    ('Sỏ'', 'Số'),
    ('láº§n', 'lần'),
    ('Nghe', 'Nghe'),
    ('gáº§n', 'gần'),
    ('token', 'token'),
    ('lưu', 'lưu'),
    ('lại', 'lại'),
    ('lỏ‹ch', 'lịch'),
    ('sỏ­', 'sử'),
    ('Lỗi', 'Lỗi'),
    ('ngÃ y', 'ngày'),
    ('trưỏ›c', 'trước'),
    ('Tuáº§n', 'Tuần'),
    ('Tháng', 'Tháng'),
    ('Top', 'Top'),
    ('Hát', 'Hát'),
    ('ðŸŽµ', '🎵'),
    ('Nháº¥n', 'Nhấn'),
    ('phát', 'phát'),
    ('BXH', 'BXH'),
    ('render', 'render'),
    ('Đ'ỏ™ng', 'động'),
    ('báº±ng', 'bằng'),
    ('JS', 'JS'),
    ('từ', 'từ'),
    ('API', 'API'),
    ('chỉ', 'chỉ'),
    ('text', 'text'),
    ('Chưa', 'Chưa'),
    ('dữ', 'dữ'),
    ('liệu', 'liệu'),
    ('Hiỏƒn', 'Hiển'),
    ('thị', 'thị'),
    ('Load', 'Load'),
    ('chưa', 'chưa'),
    ('ĐĐƒng', 'Đăng'),
    ('kÃ½', 'ký'),
    ('Xanh', 'Xanh'),
    ('dưÆ¡ng', 'dương'),
    ('VÃ ng', 'Vàng'),
    ('MÃ u', 'Màu'),
    ('nhóm', 'nhóm'),
    ('realtime', 'realtime'),
    ('autocomplete', 'autocomplete'),
    ('placeholder', 'placeholder'),
    ('Káº¿t', 'Kết'),
    ('quả', 'quả'),
    ('sẽ', 'sẽ'),
    ('ỏŸ', 'ở'),
    ('Nỏ•i', 'Nổi'),
    ('Báº­t', 'Bật'),
    ('DÃ nh', 'Dành'),
    ('cho', 'cho'),
    ('tab', 'tab'),
    ('recommended', 'recommended'),
    ('Nghệ Sĩ Đã follow', 'Nghệ Sĩ Đã follow'),
    ('â€¢', '•'),
    ('Dropdown', 'Dropdown'),
    ('menu', 'menu'),
    ('avatar', 'avatar'),
    ('profile', 'profile'),
    ('Đóng', 'Đóng'),
    ('dropdown', 'dropdown'),
    ('ra', 'ra'),
    ('ngoÃ i', 'ngoài'),
    ('Chia', 'Chia'),
    ('sáº»', 'sẻ'),
    ('mỏi', 'mời'),
    ('theo dõi', 'theo dõi'),
    ('Tỏ'i thiỏƒu', 'Tối thiểu'),
    ('kÃ½', 'ký'),
    ('tỏ±', 'tự'),
    ('Chỏ‰', 'Chỉ'),
    ('dùng', 'dùng'),
    ('chỏ¯', 'chữ'),
    ('sỏ'', 'số'),
    ('tỏ"n', 'tồn'),
    ('tại', 'tại'),
    ('cháº¯c', 'chắc'),
    ('muỏ'n', 'muốn'),
    ('xuất', 'xuất'),
    ('Táº¡o', 'Tạo'),
    ('má›i', 'mới'),
    ('LÃ m', 'Làm'),
    ('má»›i', 'mới'),
    ('Playlist', 'Playlist'),
    ('các', 'các'),
    ('playlist', 'playlist'),
    ('nhanh', 'nhanh'),
    ('Modal', 'Modal'),
    ('Ã‚m', 'Âm'),
    ('Admin', 'Admin'),
    ('Album', 'Album'),
]

fixed_count = 0
for file_path in html_files:
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original = content
        
        for wrong, correct in replacements:
            content = content.replace(wrong, correct)
        
        if content != original:
            with open(file_path, 'w', encoding='utf-8', newline='\n') as f:
                f.write(content)
            print(f'✓ Fixed: {os.path.basename(file_path)}')
            fixed_count += 1
        else:
            print(f'  OK: {os.path.basename(file_path)}')
            
    except Exception as e:
        print(f'✗ Error: {file_path} - {e}')

print(f'\n=== Done! Fixed {fixed_count} files ===')
