"""Add uploader_id to albums table

Revision ID: a360c5be2bc0
Revises: be1de514d759
Create Date: 2025-10-21 11:33:24.396838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a360c5be2bc0'
down_revision = 'be1de514d759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploader_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('albums_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['uploader_id'], ['id'])
        batch_op.create_foreign_key(None, 'artists', ['artist_id'], ['id'])

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('listening_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('listening_history_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('listening_history_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'songs', ['song_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('playlist_songs_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('playlist_songs_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'playlists', ['playlist_id'], ['id'])
        batch_op.create_foreign_key(None, 'songs', ['song_id'], ['id'])

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('playlists_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('artist_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('genre_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('songs_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('songs_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('songs_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'artists', ['artist_id'], ['id'])
        batch_op.create_foreign_key(None, 'genres', ['genre_id'], ['id'])
        batch_op.create_foreign_key(None, 'albums', ['album_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'uploader', 'user'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', mysql.VARCHAR(length=255), server_default=sa.text("'images/default.jpg'"), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('admin', 'uploader', 'user'),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('songs_ibfk_2'), 'genres', ['genre_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('songs_ibfk_1'), 'artists', ['artist_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('songs_ibfk_3'), 'albums', ['album_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('genre_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('artist_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('playlists_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('playlist_songs_ibfk_2'), 'songs', ['song_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('playlist_songs_ibfk_1'), 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('listening_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('listening_history_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('listening_history_ibfk_2'), 'songs', ['song_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('albums_ibfk_1'), 'artists', ['artist_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('uploader_id')

    # ### end Alembic commands ###
